-- Role provisioning is performed by scripts/migrate.py with a parameterized
-- identifier and a secret supplied at deployment time. This marker preserves
-- the forward-only migration history without shipping a default credential.
